# Generated by Django 3.1.4 on 2022-05-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vtocli_status',
            options={'verbose_name': 'Vendor To Client Status', 'verbose_name_plural': 'Vendor To Client Status'},
        ),
        migrations.AlterField(
            model_name='accept_request',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoonConstruction.bidcontractor'),
        ),
    ]
