# Generated by Django 3.1.4 on 2022-05-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0002_auto_20220531_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VtoCli_status',
        ),
        migrations.AlterModelOptions(
            name='accept_request',
            options={'verbose_name': 'Accept Client Request (Contractor)', 'verbose_name_plural': 'Accept Client Request (Contractor)'},
        ),
        migrations.AlterModelOptions(
            name='accept_vendor_request',
            options={'verbose_name': 'Accept Vendor Request (Contractor)', 'verbose_name_plural': 'Accept Vendor Request (Contractor)'},
        ),
        migrations.AlterModelOptions(
            name='bidcontractor',
            options={'verbose_name': 'Bid / Hire Contractor', 'verbose_name_plural': 'Bid / Hire Contractor'},
        ),
        migrations.AlterModelOptions(
            name='bidvendor',
            options={'verbose_name': 'Bid / Hire Vendor', 'verbose_name_plural': 'Bid / Hire Vendor'},
        ),
        migrations.AlterModelOptions(
            name='estimation',
            options={'verbose_name': 'Update Material Costs', 'verbose_name_plural': 'Update Material Costs'},
        ),
        migrations.AlterModelOptions(
            name='vendor_accept',
            options={'verbose_name': 'Accept Client Request (Vendor)', 'verbose_name_plural': 'Accept Client Request (Vendor)'},
        ),
        migrations.AlterModelOptions(
            name='vtoc_req',
            options={'verbose_name': 'Vendor To Contractor Request', 'verbose_name_plural': 'Vendor To Contractor Request'},
        ),
    ]
