# Generated by Django 3.1.4 on 2022-05-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
